from django.db import models

# User.
class User(models.Model):
	uname = models.CharField(max_length=30)	
	fname = models.CharField(max_length=30)	
	lname = models.CharField(max_length=30)	
	mname = models.CharField(max_length=30)	
#above our name, below sns name.
	rrname = models.CharField(max_length=30)	
	wbname = models.CharField(max_length=30)	
	fbname = models.CharField(max_length=30)	
	twname = models.CharField(max_length=30)	
	qqname = models.CharField(max_length=30)	
#other info
	date_joined = models.DateTimeField('date joined')
	ip = models.CharField(max_length=20)
	isbanned = ((u'yes'), (u'no'))
	level = models.CharField(max_length=20)

	def __unicode__(self):
		return self.uname

#	def autogenerated_name(self):
#		return self.uname='LittleAsk' + self.id

	def check_join_days(self):
		return timezone.now() - self.date_join
