from django.db import models

# User.
class front_user(models.Model):
	Email = models.EmailField()
	Password = models.CharField(max_length=30)
#other info
	def __unicode__(self):
		return self.Email

#	def autogenerated_name(self):
#		return self.uname='LittleAsk' + self.id

class back_user(models.Model):
	buser = models.ForeignKey(front_user)
#above our name, below sns name.
	fname = models.CharField(max_length=30)	
	lname = models.CharField(max_length=30)	
	mname = models.CharField(max_length=30)	
	rrname = models.CharField(max_length=30)	
	wbname = models.CharField(max_length=30)	
	fbname = models.CharField(max_length=30)	
	twname = models.CharField(max_length=30)	
	qqname = models.CharField(max_length=30)	
	joined_date = models.DateTimeField("date published")
	ip = models.CharField(max_length=20)
	isbanned = ((u'yes'), (u'no'))
	level = models.CharField(max_length=20)

	def __unicode__(self):
		return self.rrname
	def check_join_days(self):
		return timezone.now() - self.date_join
